replicaCount: 1

image:
  repository: hashicorp/http-echo
  pullPolicy: IfNotPresent
  tag: latest

args:
  - "-text=Hello from data-service"

service:
  type: ClusterIP
  port: 5678

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /
    port: 5678
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 5678
  initialDelaySeconds: 5
  periodSeconds: 5

nodeSelector: {}
tolerations: []
affinity: {}
